Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "coding-server"
  config.vm.network "private_network", ip: "192.168.99.200"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 1024
    vb.cpus = 1
  end
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo echo "mysql-server-5.5 mysql-server/root_password password password" | sudo debconf-set-selections
     sudo echo "mysql-server-5.5 mysql-server/root_password_again password password" | sudo debconf-set-selections
     sudo apt-get install -y whois git mysql-server libmysqld-dev python-pip python-dev
     sudo pip install MySQL-python flask
     mysql -uroot -p"password" -e "create database test"
     sudo useradd -m -p `mkpasswd password` -s /bin/bash dev
     sudo usermod -a -G sudo dev
     python /vagrant/init_db_user.py && python /vargrant/user.py
  SHELL
end
