# -*- mode: ruby -*-
# vi: set ft=ruby :

ROLE_NAME = 'ntp'

hosts = [
  {name: 'm1', ip: '192.168.56.71',
   net: 'private_network', box: 'bento/centos-7.2', group: 'ntpd_servers'},
  {name: 'm2', ip: '192.168.56.72',
   net: 'private_network', box: 'bento/centos-7.2', group: 'ntpd_servers'},
  {name: 'm3', ip: '192.168.56.75',
   net: 'private_network', box: 'bento/centos-7.2', group: 'workstations'}
]

Vagrant.configure(2) do |config|

   # if Vagrant.has_plugin?("vagrant-hostmanager")
   #  config.hostmanager.enabled = true     # hook to Vagrant up and vagrant destroy
   #  config.hostmanager.manage_host = true # allow /etc/hosts file updating
   #  config.hostmanager.ignore_private_ip = false # disable using the private network IP address
   #  config.hostmanager.include_offline = true # include box that are up or boxes with private IP
  # end

 N=hosts.length

  (1..N).each do |machine_id|

    config.vm.define ROLE_NAME + "-" + hosts[machine_id - 1][:name] do |node|
    # config.vm.define ROLE_NAME + "-m#{machine_id}" do |node|

      # box name
      node.vm.box = hosts[machine_id - 1][:box]
      # box hostname
      node.vm.hostname = ROLE_NAME + '-' + hosts[machine_id - 1][:name]
      # box extra interface
      node.vm.network hosts[machine_id - 1][:net], ip: hosts[machine_id - 1][:ip]

      # avoid nating through localhost
      # node.ssh.host = hosts[machine_id - 1][:ip]
      # # node.ssh.port = 22
      # node.ssh.guest_port = 22

      # Only execute once the Ansible provisioner,
      # when all the machines are up and ready.
      if machine_id == N

        config.vm.provision 'ansible' do |ansible|

          ansible.groups = {}
          ansible.host_vars = {}

          # create ansible inventory groups to allow group_vars
          # we use the box name
          for m in hosts do
            if ansible.groups.has_key?(m[:group])
              # append to list
              ansible.groups[m[:group]].push(ROLE_NAME + '-' + m[:name])
            else
              # add new key
              ansible.groups[m[:group]] = [ROLE_NAME + '-' + m[:name]]
            end

            ansible.host_vars[m[:name]] = {ansible_ssh_host:  m[:ip]}

          end

          # run the provisionner
          # ansible.verbose = 'v'
          # ansible.extra_vars = {users_debug: 'True'}
          ansible.limit = 'all'
          ansible.playbook = 'test.yml'
        end #ansible vm.provision

      end # machine_id if node.vm

    end # each loop
  end
end #vagrant.configure
