servers=[
  {
    :hostname => "mail1.lab.local",
    :box => "bento/centos-7.2",
    :ram => 512,
    :cpu => 1
  },
  {
    :hostname => "mail2.lab.local",
    :box => "bento/centos-7.2",
    :ram => 512,
    :cpu => 1
  }
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "public_network"
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram], "--cpus", machine[:cpu]]
            end
        end
    end
end

```
vagrant ssh mail1.lab.local
vagrant ssh mail2.lab.local
```
