VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 25, host: 8025
  config.vm.network :forwarded_port, guest: 110, host: 8110
  config.vm.network :forwarded_port, guest: 995, host: 8995
  config.vm.network :forwarded_port, guest: 143, host: 8143
  config.vm.network :forwarded_port, guest: 993, host: 8993
  config.vm.synced_folder "workspace", "/srv/workspace"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
end
