#!/bin/bash

#set -x
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

mysql_user=${1:-root}
mysql_passwd=${2:-"root pass"}
mysql_db=${3:-""}
mysql_wait_long_time=7200
mail_sender="check_long_query_db@example.com"
email_list=""
smtp_server=""
the_date=`date +"%Y-%m-%d %H:%S:%M"`
#log="/var/log/mysql_kill-${the_date}.log"
log="/var/log/mysql_kill.log"
interface=`route -n | grep "UG" | awk '{print $8}'`
ip=`ip a | grep "inet" | grep ${interface} | awk '{print $2}' | cut -d "/" -f 1`
msg="On `hostname` with IP=${ip}, I must kill because these queries because it runs too long > ${mysql_wait_long_time}s"
send_mail=0

function do_notify_on_error() {
  status=$1
  if [ ! -z ${smtp_server} ]; then
    [ ! $status -eq 0 ] && echo -e ${msg} | mail -s "Kill long queries on `hostname` with IP=${ip}" -S smtp=smtp://${smtp_server} -S from="${mail_sender}" ${email_list}
  else
    [ ! $status -eq 0 ] && echo -e ${msg} | mail -s "Kill long queries on `hostname` with IP=${ip}" -S from="${mail_sender}" ${email_list}
  fi
}

[ -z ${mysql_db} ] && ids=$(mysql -u${mysql_user} -p"${mysql_passwd}" -Ane "show full processlist" | grep "Query"  | grep "Sending data" | awk '{print $1"-"$2"-"$3"-"$4"-"$6}') || ids=$(mysql -u${mysql_user} -p"${mysql_passwd}" -Ane "show full processlist" | grep "${mysql_db}" | grep "Query"  | grep "Sending data" | awk '{print $1"-"$2"-"$3"-"$4"-"$6}')
for query_id in ${ids}; do
  echo $query_id
  id=`echo ${query_id} | cut -d "-" -f 1`
  user=`echo ${query_id} | cut -d "-" -f 2`
  host=`echo ${query_id} | cut -d "-" -f 3`
  db=`echo ${query_id} | cut -d "-" -f 4`
  query_time=`echo ${query_id} | cut -d "-" -f 5`
  info=$(mysql -u${mysql_user} -p"${mysql_passwd}" -Ane "SELECT info FROM information_schema.processlist where id=${id}" | grep -v "info")
  if [[ ( ${query_time} -gt ${mysql_wait_long_time} ) && ( ${id} -gt 0 ) ]]; then
    send_mail=1
    query="
        id=${id}
        user=${user}
        host=${host}
        db=${db}
        info=${info}
    "
    echo "KILLING $query..."
    ## send log
    the_date=`date +"%Y-%m-%d %H:%S:%M"`
    echo "======================= ${the_date} ======================" >> ${log}
    echo "${query}" >> ${log}
    ## killquery
    mysql -u${mysql_user} -p"${mysql_passwd}" -e "kill ${id}";
  fi
done
[ ${send_mail} -eq 1 ] && do_notify_on_error 1

